channels:
  - conda-forge
  - bioconda
dependencies:
  - python = 3.9
  - pymysql
  - cloud-sql-python-connector[pymysql]
  - sqlalchemy
  - pandas
  - locationtagger
  - googlemaps
  - requests
  - argparse
